version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: coachly_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: coachly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
